import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import type { PokemonPlush } from "@prisma/client";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useState } from "react";
import { Toaster } from "react-hot-toast";
import PokemonCard from "~/components/Card";
import CommentSection from "~/components/CommentSection";
import { prisma } from "~/server/prisma";
export const getServerSideProps: GetServerSideProps = async () => {
  const firstPlush = await prisma.pokemonPlush.findFirst();
  return {
    props: {
      firstPokemon: firstPlush,
    },
  };
};
type Props = {
  firstPokemon: PokemonPlush | null;
};
export default function Home({ firstPokemon }: Props) {
  if (!firstPokemon) return <></>;
  const [selected, setSelected] = useState(firstPokemon);
  return (
    <>
      <Head>
        <title>Pokemon Plush</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Container
          maxWidth="lg"
          sx={{
            height: {
              md: "100vh",
            },
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Box
            sx={{
              width: "100%",
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
            }}
          >
            <Grid container spacing={2} alignItems="center">
              <Grid item xs={12} md={6}>
                <PokemonCard selected={selected} setSelected={setSelected} />
              </Grid>
              <Grid item xs={12} md={6}>
                <CommentSection selectedId={selected.id} />
              </Grid>
            </Grid>
          </Box>
          <Toaster />
        </Container>
      </main>
    </>
  );
}
