import { Box, Container, Grid } from "@mui/material";
import type { PokemonPlush } from "@prisma/client";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useState } from "react";
import { Toaster } from "react-hot-toast";
import PokemonCard from "~/components/Card";
import CommentSection from "~/components/CommentSection";
import { prisma } from "~/server/prisma";
export const getServerSideProps: GetServerSideProps = async () => {
  const firstPlush = await prisma.pokemonPlush.findFirst();
  return {
    props: {
      firstPokemon: firstPlush,
    },
  };
};
type Props = {
  firstPokemon: PokemonPlush;
};
export default function Home({ firstPokemon }: Props) {
  const placeholder: PokemonPlush = {
    id: "6429605255d3563f0ea24f75",
    name: "Litten",
    plushName: "ピカピカバッグ Pika Pika Bag 2017 plush keychain + mug",
    url: "https://i.ibb.co/44Hz4MX/4521329208787-03-L-Copy-2.jpg",
  };
  const [selected, setSelected] = useState(firstPokemon || placeholder);
  return (
    <>
      <Head>
        <title>Pokemon Plush</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Container
          maxWidth="lg"
          sx={{
            height: "100vh",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Box
            sx={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              m: 2,
            }}
          >
            <Grid container spacing={2}>
              <Grid item xs={12} md={6}>
                <PokemonCard selected={selected} setSelected={setSelected} />
              </Grid>
              <Grid item xs={12} md={6}>
                <CommentSection selectedId={selected.id} />
              </Grid>
            </Grid>
          </Box>
          <Toaster />
        </Container>
      </main>
    </>
  );
}
